### ISSUE TITLE
When loading an image file to convert to G-Code, Tools are being listed as machine configurations. 

### ISSUE THREAD

**Issue by virtuoushub** [MarginallyClever/Makelangelo#105]
![screen shot 2015-05-25 at 1 41 39 pm](https://cloud.githubusercontent.com/assets/4303638/7800477/e4513a9a-02e3-11e5-886d-bc7eba209356.png)

#95 is most likely to blame. ~~I suspect this issue I am seeing is local to my environment; as I have blown out and changed the location of preference values when testing.~~ I am in the process of writing unit tests for preferences (#74), as well as a writing a tool to help import and export preference values.

~~Possibly~~ [Probably not](https://github.com/MarginallyClever/Makelangelo/issues/102#issuecomment-105282700) related to #102.

**Comment by i-make-robots** [comment]
It seems heirarchy of preferences has changed and it broke way configurations_available is initialized in MachineConfiguration().  Either that or preferences.childrenNames() doesn't behave as it used to.  I had set it up withe [root/machine number/tool name], and preferences.childrenNames() is returning both machine number and all tool name.

**Comment by i-make-robots** [comment]
Submitted a fix that filters out all names that don't match the number format.  this is less-than-ideal, as the tool names should not have shown up in this list.  Also on my laptop there are at least 6 machine profiles and I'm only getting one listed, which means the problem could run deeper.  Could other profiles have been wiped somehow?  Are they lost in the twilight zone?

**Comment by virtuoushub** [comment]
Not wiped, just residing in a different preference node. I either need to I revert the preference node locations from [com.marginallyclever.makelangelo](https://github.com/MarginallyClever/Makelangelo/blob/dev/java/src/main/java/com/marginallyclever/makelangelo/PreferencesHelper.java#L27) back to DrawBot and the other respective locations or have a tool that maps/moves from the old location to the new.

I have a some tests written for the preferences that recursively prints out the values for a given node. When I get some time I'll open a pull request the aforementioned unit tests. I suspect [Preferences#childrenNames()](https://docs.oracle.com/javase/7/docs/api/java/util/prefs/Preferences.html#childrenNames()) did not change, I probably borked the logic so that [root/machine number/tool name] became [root/tool name]. I am in the process of fixing it so that it was like it was and so that you don't have to filter out names that do not match the number format.

**Comment by i-make-robots** [comment]
I know right now when I loads home 551 it only shows me settings for 692. :(

**Comment by i-make-robots** [comment]
@virtuoushub, your latest pull seems to fix the issue.  Good job!  I believe the last outstanding issue is to teach me how to properly export so I can update the release package with these fixes.

**Comment by virtuoushub** [comment]
@i-make-robots, when I write it the instructions on how to export will be [here](https://github.com/MarginallyClever/Makelangelo/wiki#exporting-a-jar-file).
