### ISSUE TITLE
Tag v7.1.1, v7.1.2, and v7.1.3

### ISSUE THREAD

**Issue by virtuoushub** [MarginallyClever/Makelangelo#109]
* Master branch at commit: 6c6e0ade17828995e9e0515d5ad2029253f1e471 should be [v7.1.1](https://github.com/MarginallyClever/Makelangelo/tree/6c6e0ade17828995e9e0515d5ad2029253f1e471)
```shell
git tag -a v7.1.1 -m 'Release version v7.1.1' 6c6e0ad
git push origin v7.1.1 
```
* Master branch at commit: 463c0b9f1b6a16a824fdcaa8708115684e1c6cdf should be [v7.1.2](https://github.com/MarginallyClever/Makelangelo/tree/463c0b9f1b6a16a824fdcaa8708115684e1c6cdf)
```shell
git tag -a v7.1.2 -m 'Release version v7.1.2' 463c0b9
git push origin v7.1.2
```

* Master branch at commit: c82ccecc47d99723932576f897b69b4f66eb567c  should be [v7.1.3](https://github.com/MarginallyClever/Makelangelo/tree/c82ccecc47d99723932576f897b69b4f66eb567c)
```shell
git tag -a v7.1.3 -m 'Release version v7.1.3' c82ccec
git push origin v7.1.3
```

For [v7.1.1](https://github.com/MarginallyClever/Makelangelo/tree/6c6e0ade17828995e9e0515d5ad2029253f1e471), just the source should be included as the release jar was never updated appropriately.

When a more [formalized process is documented](https://github.com/MarginallyClever/Makelangelo/wiki#exporting-a-jar-file), these types of issues will go away.

**Comment by i-make-robots** [comment]
Can i do this from within the github app?

**Comment by virtuoushub** [comment]
@i-make-robots, IIRC the GitHub app has a place to launch the terminal, so yes you can run the commands there.

In terms of doing it through the GUI, I use [SourceTree](https://www.sourcetreeapp.com/) and know you can do it through the GUI in that. I have not used the GitHub app in a long time so I can not say for sure. Which version of it are you using(Windows, Mac, ...)?

**Comment by i-make-robots** [comment]
Done.
