### ISSUE TITLE
Recent Line Inaccuracy

### ISSUE THREAD

**Issue by chrsmlls333** [MarginallyClever/Makelangelo#110]
Noticeable curtaining effect which is new in the past months firmware updates. 
![](http://i.imgur.com/LXeBTe3.jpg)

Has anyone noticed this? The top line is intervals of 10 on the manual controls and the bottom arced line is one movement of 100.

**Comment by i-make-robots** [comment]
The firmware splits long lines into short segments to cancel out this
bowing problem.  the MM_PER_SEGMENT value may be too high.  There's also a
chance that drag on the pen tip is causing the line to bend a little bit on
longer movements.

On Wed, Jun 3, 2015 at 5:26 PM, Chris Mills <notifications@github.com>
wrote:

> Noticeable curtaining effect which is new in the past months firmware
> updates.
>
> <https://camo.githubusercontent.com/d7bfe60055cf0fd6790c84ff0145e852721b0115/687474703a2f2f692e696d6775722e636f6d2f4c5865425465332e6a7067>
>
> Has anyone noticed this? The top line is intervals of 10 on the manual
> controls and the bottom arced line is one movement of 100.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarginallyClever/Makelangelo/issues/110>.
>



-- 
Dan Royer :: Marginally Clever <http://www.marginallyclevergroup.com/> ::
Raising Robot Literacy :: +1.604.916.2281

**Comment by chrsmlls333** [comment]
Thanks I'll compare the mmPer values of the two firmware versions and get back on if that solves it.

**Comment by chrsmlls333** [comment]
Changing MM_PER_SEGMENT from 10 to 3 or 4 fixed this. Easy peasy thanks a lot.
