### ISSUE TITLE
Remove Eclipse specific files from project. 

### ISSUE THREAD

**Issue by virtuoushub** [MarginallyClever/Makelangelo#111]
c19ecb52681f1e3b6857627133f1cecdf6cefffe reintroduced the .project file, .settings/ folder, and introduced the [classes](https://github.com/MarginallyClever/Makelangelo/tree/dev/java/classes) folder which is auto generated by Eclipse.

These files and folders tend to be specific to one developer's environment.

The Eclipse gitignore template https://github.com/github/gitignore/blob/master/Global/Eclipse.gitignore ignores them and I think it Makelangelo should too.

### Suggested fix snippet
```shell
git rm -r --cached java/.project
```
From the [Git docs](http://git-scm.com/docs/git-rm#_options):

```
--cached
Use this option to unstage and remove paths only from the index. Working tree files, whether modified or not, will be left alone.
```

To the person running that command it essential means: Git stop tracking this file in the repository but leave it alone in my local file system.

**Comment by i-make-robots** [comment]
ran this on both .project and .settings.  Does that work?

**Comment by virtuoushub** [comment]
Yes thanks. 8ad26076cd7fd09f497bbe0046533a2ba06c49a5 did the trick.
