### ISSUE TITLE
text to gcode font calculations broken

### ISSUE THREAD

**Issue by i-make-robots** [MarginallyClever/Makelangelo#118]
Semething in text to gcode is broke.  it calculates a maximum of one character per line across the page, even when many more would fit.

**Comment by virtuoushub** [comment]
Does this still occur?

I tested on 71221999023457718e97f3f05c67b9d16e71ef1a and I was unable to reproduce.
![screen shot 2015-06-25 at 10 40 13 am](https://cloud.githubusercontent.com/assets/4303638/8357051/d146c176-1b26-11e5-982d-a81c6eab3d65.png)

**Comment by i-make-robots** [comment]
I fixed it in the last commit. Seems to be confirmed fixed now. Nice!
