### ISSUE TITLE
Document MarginallyCleverPreferencesHelper

### ISSUE THREAD

**Issue by virtuoushub** [MarginallyClever/Makelangelo#125]
A while back I wrote a helper class to remove illegal preference nodes(machine names < 0)

@i-make-robots Check out [MarginallyCleverPreferencesHelper](https://github.com/MarginallyClever/Makelangelo/blob/dev/java/src/main/java/com/marginallyclever/util/MarginallyCleverPreferencesHelper.java#L30-L38) if [PreferencesHelperTest]( https://github.com/MarginallyClever/Makelangelo/blob/dev/java/src/test/java/com/marginallyclever/makelangelo/PreferencesHelperTest.java) is failing.

The helper class removes all machines whose name is -1 or below.

Which, in turn, will cause [PreferencesHelperTest#testMachineConfigurationNames()](https://github.com/MarginallyClever/Makelangelo/blob/dev/java/src/test/java/com/marginallyclever/makelangelo/PreferencesHelperTest.java#L96-L112) to pass.

Because MarginallyCleverPreferencesHelper has:
```java
...
public static void main(String[] args) throws BackingStoreException {
...
```
You can run it as a Java application from your IDE. See the Eclipse documentation for [Running your programs](http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2FgettingStarted%2Fqs-12.htm) on how to do this in Eclipse.

This is an undocumented feature with no public API built mostly for me as a convenience tool to cleanse any invalid preferences that somehow made their way in.

**Comment by virtuoushub** [comment]
This issue and Javadocs are sufficient documentation.

**Comment by Jip-Hop** [comment]
I'm trying to get rid of machines with ids < 0, but this solution no longer seems to work. Where is the config stored for each machine? I've been looking everywhere. 😝
