### ISSUE TITLE
Etch-a Sketch: Up/Down and Go Home

### ISSUE THREAD

**Issue by chrsmlls333** [MarginallyClever/Makelangelo#136]
Hey there! Loving the Etch a Sketch feature but it replaced Up/Down control and the Go Home button which were incredibly useful for testing. Are those coming back?

**Comment by chrsmlls333** [comment]
Or if you have an alternative method, by all means. It would be interesting to see the Etch a sketch have a grid for positioning and/or safe zone in the middle that triggers centering if clicked.

**Comment by i-make-robots** [comment]
I just put the up/down/set home controls back into the dev version.

The click & drag is unchanged.  They're absolute coordinates - a dead zone would mean you couldn't draw in the middle of the picture.

**Comment by chrsmlls333** [comment]
Cheers
