### ISSUE TITLE
Doxygen?

### ISSUE THREAD

**Issue by virtuoushub** [MarginallyClever/Makelangelo#140]
Commit 504a5896c8cab3ddcb3f6de0549b685d686e9a5a added the file: `java/Makelangelo.doxyfile`

Is there a reason to use this over Javadoc? ~~(aside from the Javadocs being mostly nonexistent and totally fucked when they are written...)~~ :smirk_cat: 

From the command line(can also be accomplished in Eclipse):
```
java/mvnw javadoc:javadoc
```
[javadoc:javadoc](https://maven.apache.org/plugins/maven-javadoc-plugin/javadoc-mojo.html)
That command will generate you an html version of your documentation. It is one of the many reasons I added the use of a build tool like Maven.

**Comment by i-make-robots** [comment]
Some people asked for doxygen on another project.  I'll just leave the file
there and let them generate doxygen files when they need to.  generated
files are ignored from the repo.

On Tue, Sep 29, 2015 at 6:55 AM, Peter Colapietro <notifications@github.com>
wrote:

> Commit 504a589
> <https://github.com/MarginallyClever/Makelangelo/commit/504a5896c8cab3ddcb3f6de0549b685d686e9a5a>
> added the file: java/Makelangelo.doxyfile
>
> Is there a reason to use this over Javadoc? (aside from the Javadocs
> being mostly nonexistent and totally fucked when they are written...) [image:
> :smirk_cat:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarginallyClever/Makelangelo/issues/140>.
>



-- 
Dan Royer :: Marginally Clever <http://www.marginallyclevergroup.com/> ::
Raising Robot Literacy :: +1.604.916.2281

**Comment by virtuoushub** [comment]
Closing per @i-make-robots' [comment](https://github.com/MarginallyClever/Makelangelo/issues/140#issuecomment-144030438).
