### ISSUE TITLE
Reduce pen wobble with better pen holder

### ISSUE THREAD

**Issue by i-make-robots** [MarginallyClever/Makelangelo#162]
Something like http://www.thingiverse.com/thing:798076 but made for timing belt.
Marginally Clever has permission to make a modified version of said thingiverse part and include it in the kits.

**Comment by devburke** [comment]
The one thing to be careful about is the long rigid arms. I've been using a Mega Sketch from Brown Dog Gadgets, and it has long acrylic arms that the belts are attached to. Pushed to the extremes of the drawing area, it's been getting distorted. My theory is that the arms through off the trigonometry when the angle they're at gets farther away from the angle between the pen and the steppers. I think it's best to have the belts attach as close to the pen as possible.

**Comment by i-make-robots** [comment]
The arms should swivel around the pen.  Got a url for the version you're
using?

On Sat, Apr 23, 2016 at 9:51 AM, Devin Burke <notifications@github.com>
wrote:

> The one thing to be careful about is the long rigid arms. I've been using
> a Mega Sketch from Brown Dog Gadgets, and it has long acrylic arms that the
> belts are attached to. Pushed to the extremes of the drawing area, it's
> been getting distorted. My theory is that the arms through off the
> trigonometry when the angle they're at gets farther away from the angle
> between the pen and the steppers. I think it's best to have the belts
> attach as close to the pen as possible.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/MarginallyClever/Makelangelo/issues/162#issuecomment-213781094>
>



-- 
Dan Royer, Owner, Marginally Clever Robots
<https://www.marginallyclever.com/>
Ph: +1 (604) 259-9564
Mo: +1 (604) 916-2281

**Comment by devburke** [comment]
Agreed. I’m thinking of making a replacement for that part.

It’s here: http://www.browndoggadgets.com/collections/robotics/products/mega-sketch

and can be seen up close here https://cdn.shopify.com/s/files/1/0191/2838/products/IMG_5337_1024x1024.jpg?v=1440622913

Someone else built this one and was what introduced me to the idea of these things.

**Comment by i-make-robots** [comment]
Wow. That's the same text I used to have on the makelangelo website. Come on, brown dog. Where is the love?

**Comment by devburke** [comment]
Ooh, that is rough. These ideas are definitely out there (see http://www.polargraph.co.uk/whats-a-polargraph/), but this ships with Makelangelo firmware, and pulls your text too? I know it’s open source, but some upfront credit would be nice.

**Comment by devburke** [comment]
Of course! I hope you don’t mind that I’ve been making my own? I took how open source it all is to mean that you were open to it. It’s both a learning experience for me, and I don’t think I would’ve been in a spot to afford a kit. I have been planning on donating a bit once it’s finished. Hopefully what I lack in funds is somewhat made up for in contribution here :)

**Comment by i-make-robots** [comment]
It's open source exactly for those who can't afford it. The next group is people who just want to use a machine and don't want to assemble it. With this robot I make my money on the second group... And sometimes support donations.

**Comment by i-make-robots** [comment]
Clear penholder seems much better, I'm quite satisfied.  I consider this issue closed as this pen holder is starting to trickle out to the real world.

**Comment by Joshua-BrownDogGadgets** [comment]
Josh from Brown Dog Gadgets.  

Dan, you know full well WHY the text is the same.  Stop playing the "woah is me" card.

We originally started reselling Makelangelo Kits made 100% by you.  Then we started selling hardware SOURCED FROM YOU but with our own acrylic because you refuse to improve your laser cutting or institute the very simple and obvious change of using a CLEAR pen holder.  You know, so people can SEE what they're drawing.  Something we suggested to you two years ago.  

So yes, we are shameless using text that is copy and pasted off your website... because we are reselling kits that we have BOUGHT FROM YOU IN BULK.  

But you're right, we should change it.  The last thing we want to do is hurt your feelings or buy more supplies from.

**Comment by i-make-robots** [comment]
@Joshua-BrownDogGadgets are you OK?  I move as fast as I can to act on all the feedback I get and yes, sometimes it can take years.

My issue with identical text is that it hurts your SEO and mine.  Google notices stuff like that.  Thanks for changing it.

**Comment by Joshua-BrownDogGadgets** [comment]
Dan,

Your line of comments were insulting.  To anyone viewing them it would
appear as if we were ripping you off, when we have only been using parts
from you to make these machines.  That's what I take issue with. It's a
nice "fuck your" to someone who has spent a decent chunk of money buying
stuff from you.

If it's messing with SEO, just ask us to change it.

I still can't get any machine to work in our shop to work with the new
firmware and software.  Every single one has a motor slipping.  Every time.
Polar graph and core xy.  Looking at the forums it seems I'm not the only
one.  If I can't get it to work in my shop how can I sell it to customers.

I've got a museum in South Carolina who wants 20 machines, but I've put
them on a holding pattern because we can't get thing to work in shop.

Again, all parts are from you.  All software is from you.  I'm growing
tired of spending my evening trying to trouble shoot things that should
work.

Joshua

On Thursday, June 9, 2016, Dan Royer <notifications@github.com> wrote:

> @Joshua-BrownDogGadgets <https://github.com/Joshua-BrownDogGadgets> are
> you OK? I move as fast as I can to act on all the feedback I get and yes,
> sometimes it can take years.
>
> My issue with identical text is that it hurts your SEO and mine. Google
> notices stuff like that. Thanks for changing it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/MarginallyClever/Makelangelo/issues/162#issuecomment-225069779>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AS7cT6rV5jNu-yxlJS45oB4focknjAY_ks5qKLiigaJpZM4HGYCJ>
> .
>


-- 
Joshua Zimmerman
BrownDogGadgets.com
P: 262-788-9223
C: 262-290-6630

**Comment by Joshua-BrownDogGadgets** [comment]
Whichever motor moves last locks.  The other one is loose.  Happens in both
core xy and polar graph.

Latest version of your software and firmware.

Entirely 100% your hardware.

We had to take our wall mounted unit off the wall as it was the only one
working in the office.  Needed it for a show.

Joshua

On Thursday, June 9, 2016, Joshua Zimmerman <joshua@browndoggadgets.com>
wrote:

> Dan,
>
> Your line of comments were insulting.  To anyone viewing them it would
> appear as if we were ripping you off, when we have only been using parts
> from you to make these machines.  That's what I take issue with. It's a
> nice "fuck your" to someone who has spent a decent chunk of money buying
> stuff from you.
>
> If it's messing with SEO, just ask us to change it.
>
> I still can't get any machine to work in our shop to work with the new
> firmware and software.  Every single one has a motor slipping.  Every time.
> Polar graph and core xy.  Looking at the forums it seems I'm not the only
> one.  If I can't get it to work in my shop how can I sell it to customers.
>
> I've got a museum in South Carolina who wants 20 machines, but I've put
> them on a holding pattern because we can't get thing to work in shop.
>
> Again, all parts are from you.  All software is from you.  I'm growing
> tired of spending my evening trying to trouble shoot things that should
> work.
>
> Joshua
>
> On Thursday, June 9, 2016, Dan Royer <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> @Joshua-BrownDogGadgets <https://github.com/Joshua-BrownDogGadgets> are
>> you OK? I move as fast as I can to act on all the feedback I get and yes,
>> sometimes it can take years.
>>
>> My issue with identical text is that it hurts your SEO and mine. Google
>> notices stuff like that. Thanks for changing it.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/MarginallyClever/Makelangelo/issues/162#issuecomment-225069779>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AS7cT6rV5jNu-yxlJS45oB4focknjAY_ks5qKLiigaJpZM4HGYCJ>
>> .
>>
>
>
> --
> Joshua Zimmerman
> BrownDogGadgets.com
> P: 262-788-9223
> C: 262-290-6630
>
>

-- 
Joshua Zimmerman
BrownDogGadgets.com
P: 262-788-9223
C: 262-290-6630

**Comment by i-make-robots** [comment]
I'm heading into a maker fair this weekend.  I was aware of the issue, and I will continue investigating the cause on Monday.

I have no desire to insult you.  I didn't realize it would come across that way.

**Comment by Joshua-BrownDogGadgets** [comment]
Several of us here saw it and it came across that way to everyone.

Let me know how to fix that problem.  I've either got to cancel some
customer orders or figure out a way of fixing things.

On Fri, Jun 10, 2016 at 2:42 PM, Dan Royer <notifications@github.com> wrote:

> I'm heading into a maker fair this weekend. I was aware of the issue, and
> I will continue investigating the cause on Monday.
>
> I have no desire to insult you. I didn't realize it would come across that
> way.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/MarginallyClever/Makelangelo/issues/162#issuecomment-225277173>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AS7cT6gwUkMziS0ycMTBElmXJohECxFUks5qKb4dgaJpZM4HGYCJ>
> .
>



-- 
Joshua Zimmerman
BrownDogGadgets.com
P: 262-788-9223
C: 262-290-6630

**Comment by i-make-robots** [comment]
I've been working on it since it was first reported. I'll let you know ASAP.
