### ISSUE TITLE
Use OS-appropriate keyboard shortcut modifier keys

### ISSUE THREAD

**Issue by mouseas** [MarginallyClever/Makelangelo#170]
Currently commands with any keyboard shortcuts, such as Zoom In and Zoom Out, use the Alt key. Users on Windows expect to use the Ctrl key, while Mac users expect to use the Command key. Java has faculties to determine which key is appropriate for the OS it's currently running on.

Take a look at java.awt.Toolkit: `Toolkit.getDefaultToolkit().getMenuShortcutKeyMask()` will get Command key for Mac, and Ctrl for Windows.

**Comment by i-make-robots** [comment]
Huh.  I did not know that! :)

Can you put it in the code and send a pull request?

On Sat, Apr 9, 2016 at 4:11 PM, Martin <notifications@github.com> wrote:

> Currently commands with any keyboard shortcuts, such as Zoom In and Zoom
> Out, use the Alt key. Users on Windows expect to use the Ctrl key, while
> Mac users expect to use the Command key. Java has faculties to determine
> which key is appropriate for the OS it's currently running on.
>
> Take a look at java.awt.Toolkit:
> Toolkit.getDefaultToolkit().getMenuShortcutKeyMask() will get Command key
> for Mac, and Ctrl for Windows.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/MarginallyClever/Makelangelo/issues/170>
>



-- 
Dan Royer, Owner, Marginally Clever Robots
<https://www.marginallyclever.com/>
Ph: +1 (604) 259-9564
Mo: +1 (604) 916-2281
