### ISSUE TITLE
Refuse to draw until homed

### ISSUE THREAD

**Issue by i-make-robots** [MarginallyClever/Makelangelo#172]
Makelangelo software should refuse to start a drawing until the machine has been homed.  Assuming the machine is homed at startup is potential disaster.

**Comment by devburke** [comment]
Agreed. This should be managed somehow. Accidentally clicking "Start" before returning to home means the user has to stop and find home all over again.

**Comment by i-make-robots** [comment]
I am looking into this bug right now.

On Sat, Apr 23, 2016 at 9:48 AM, Devin Burke <notifications@github.com>
wrote:

> Agreed. This should be managed somehow. Accidentally clicking "Start"
> before returning to home means the user has to stop and find home all over
> again.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/MarginallyClever/Makelangelo/issues/172#issuecomment-213779442>
>



-- 
Dan Royer, Owner, Marginally Clever Robots
<https://www.marginallyclever.com/>
Ph: +1 (604) 259-9564
Mo: +1 (604) 916-2281

**Comment by i-make-robots** [comment]
Tentative fix implemented.  Can you build and test on your end?

**Comment by devburke** [comment]
Would if I could, but I left mine at work over the weekend, won’t have access to it until Monday.
