### ISSUE TITLE
Start At Line not working

### ISSUE THREAD

**Issue by devburke** [MarginallyClever/Makelangelo#173]
Currently, the "Start at line" button just starts at the beginning, every time. I'm not at a computer where I can test this, but I believe it's due to an error in the startAt() method in Makelangelo/java/src/main/java/com/marginallyclever/makelangelo/Makelangelo.java

The method contains the following code right now:

	public void startAt(long lineNumber) {

		gCode.setLinesProcessed(0);

		robot.sendLineToRobot("M110 N" + gCode.getLinesProcessed());

		cameraViewPanel.setLinesProcessed(gCode.getLinesProcessed());

		startDrawing();

	}

It takes in a lineNumber parameter, and then never uses it. As far as I can tell, the first command
`gCode.setLinesProcessed(0);`
should be
`gCode.setLinesProcessed(lineNumber);`

You can see in Makelangelo/java/src/main/java/com/marginallyclever/makelangeloRobot/MakelangeloRobotPanel.java that this code:

		if (subject == buttonStart) {

			gui.startAt(0);

			updateButtonAccess(robot.isPortConfirmed(), true);

			return;

		}

		if (subject == buttonStartAt) {

			Long lineNumber = getStartingLineNumber();

			if (lineNumber != -1) {

				gui.startAt(lineNumber);

			}

			updateButtonAccess(robot.isPortConfirmed(), true);

			return;

		}

calls startAt() and passes in a 0 if the start button is pushed, and passes in another number if the start at line button is pushed. As it is though, the called method always uses 0, instead of looking at the parameter.

**Comment by i-make-robots** [comment]
Appears fixed in commit 8b981d19a80ad3e6d809564cad0d1e50eaf5a9c8
