### ISSUE TITLE
Sandy Noble Style bottom right option incorrect. 

### ISSUE THREAD

**Issue by cruisetheblues** [MarginallyClever/Makelangelo#175]
When choosing sandy noble style, choosing the bottom right option creates a pattern starting from the bottom left. The bottom left option also starts at the bottom left so I believe it's just a singular issue. Hopefully it's an easy fix.

**Comment by i-make-robots** [comment]
fixed in dev branch commit aa86d3a6572c674b1d8616d6664a678fe1e49373

On Sat, Apr 30, 2016 at 6:59 PM, cruisetheblues <notifications@github.com>
wrote:

> When choosing sandy noble style, choosing the bottom right option creates
> a pattern starting from the bottom left. The bottom left option also starts
> at the bottom left so I believe it's just a singular issue. Hopefully it's
> an easy fix.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/MarginallyClever/Makelangelo/issues/175>
>



-- 
Dan Royer, Owner, Marginally Clever Robots
<https://www.marginallyclever.com/>
Ph: +1 (604) 259-9564
Mo: +1 (604) 916-2281
