### ISSUE TITLE
v7.4.5 wasting time on draw

### ISSUE THREAD

**Issue by devburke** [MarginallyClever/Makelangelo#178]
Previously, the bot would move directly to the next line it wanted to draw. If there was a big region with no lines to draw, it would skip past it and move directly to the beginning of the next line.

On the latest versions, it seems to move back and forth across the entire drawing, whether it's drawing in a particular area or not. This means it takes a lot more time than necessary, but it also means that it risks drying out the markers by having them spend so much time not drawing while they're uncapped.

**Comment by i-make-robots** [comment]
DXF files?  It has to do with the order lines are stored in the DXF format.  I just read them in and draw them in that order.  No attempt at re-routing is done.

**Comment by devburke** [comment]
Just regular converted jpegs.

**Comment by i-make-robots** [comment]
What conversion style?

On Thu, May 12, 2016 at 9:24 AM, Devin Burke <notifications@github.com>
wrote:

> Just regular converted jpegs.
>
>
>
> > On May 12, 2016, at 11:23 AM, Dan Royer <notifications@github.com>
> wrote:
> >
> > DXF files? It has to do with the order lines are stored in the DXF
> format. I just read them in and draw them in that order. No attempt at
> re-routing is done.
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/MarginallyClever/Makelangelo/issues/178#issuecomment-218810411>
>



-- 
Dan Royer, Owner, Marginally Clever Robots
<https://www.marginallyclever.com/>
Ph: +1 (604) 259-9564
Mo: +1 (604) 916-2281

**Comment by devburke** [comment]
Crosshatch. It’s almost exclusively the one I use, cuz it looks great, even if it is slow to draw.

**Comment by i-make-robots** [comment]
So it's travelling back and forth over the empty parts of the picture?  I
think I know what that is and I believe it's fixed in dev.  will be in the
7.5.0 release (tomorrow?)

On Thu, May 12, 2016 at 9:26 AM, Devin Burke <notifications@github.com>
wrote:

> Crosshatch. It’s almost exclusively the one I use, cuz it looks great,
> even if it is slow to draw.
>
>
>
> > On May 12, 2016, at 11:25 AM, Dan Royer <notifications@github.com>
> wrote:
> >
> > What conversion style?
> >
> > On Thu, May 12, 2016 at 9:24 AM, Devin Burke <notifications@github.com>
> > wrote:
> >
> > > Just regular converted jpegs.
> > >
> > >
> > >
> > > > On May 12, 2016, at 11:23 AM, Dan Royer <notifications@github.com>
> > > wrote:
> > > >
> > > > DXF files? It has to do with the order lines are stored in the DXF
> > > format. I just read them in and draw them in that order. No attempt at
> > > re-routing is done.
> > > >
> > > > —
> > > > You are receiving this because you authored the thread.
> > > > Reply to this email directly or view it on GitHub
> > > >
> > >
> > > —
> > > You are receiving this because you commented.
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/MarginallyClever/Makelangelo/issues/178#issuecomment-218810411
> >
> > >
> >
> >
> >
> > --
> > Dan Royer, Owner, Marginally Clever Robots
> > <https://www.marginallyclever.com/>
> > Ph: +1 (604) 259-9564
> > Mo: +1 (604) 916-2281
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub <
> https://github.com/MarginallyClever/Makelangelo/issues/178#issuecomment-218810828
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/MarginallyClever/Makelangelo/issues/178#issuecomment-218811036>
>



-- 
Dan Royer, Owner, Marginally Clever Robots
<https://www.marginallyclever.com/>
Ph: +1 (604) 259-9564
Mo: +1 (604) 916-2281

**Comment by devburke** [comment]
Yep. It didn’t used to do that, so it must have been a recent change somehow.

**Comment by devburke** [comment]
Still having this issue on 7.5.

**Comment by devburke** [comment]
Combined with steppers which are moving crazy slow, this makes for some extremely long draw times.

**Comment by devburke** [comment]
Strangely, I'm finding that I can't go back to an earlier version either. Even if I flash the Uno, on any version except the latest, the Start button will never activate.

**Comment by i-make-robots** [comment]
Must hit home before start will activate.

**Comment by devburke** [comment]
Tried that.

**Comment by i-make-robots** [comment]
Are you running a stock 3.2 or 2.5.2 kit?

**Comment by devburke** [comment]
I'm running the homemade kit, but I believe it's modeled after 2.5.2 (needs to be tethered to a computer).

The latest version works fine, but running an older version, I can't get the start button to activate at all.

**Comment by i-make-robots** [comment]
email me your phone number, I'll walk you through how to debug this.

**Comment by i-make-robots** [comment]
Is this still happening?  I can't debug a home-made kit as I have no matching hardware.

**Comment by devburke** [comment]
Makes sense. Although this one's actually the kit that came from Brown Dog. Either way, I don't have access to it anymore fur a long while. I'm leaving the country for awhile, so at this point it's someone else's worry to get it running right :) I didn't have time to try much. I tried an older firmware, but I spent more of my time figuring out why that other shield wasn't working.

**Comment by i-make-robots** [comment]
Brown Dog got their kits from us.  Since then we've started fully
assembling our kits to reduce the number of potential problems.

On Mon, Jun 20, 2016 at 5:10 PM, Devin Burke <notifications@github.com>
wrote:

> Makes sense. Although this one's actually the kit that came from Brown
> Dog. Either way, I don't have access to it anymore fur a long while. I'm
> leaving the country for awhile, so at this point it's someone else's worry
> to get it running right :) I didn't have time to try much. I tried an older
> firmware, but I spent more of my time figuring out why that other shield
> wasn't working.
>
>
>
> > On Jun 20, 2016, at 5:04 PM, Dan Royer <notifications@github.com> wrote:
> >
> > Is this still happening? I can't debug a home-made kit as I have no
> matching hardware.
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/MarginallyClever/Makelangelo/issues/178#issuecomment-227306332>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABZYhqIiO-49OUUTvWX3R62zfEcTFBxjks5qNyvpgaJpZM4IdOlm>
> .
>



-- 
Dan Royer, Owner, Marginally Clever Robots
<https://www.marginallyclever.com/>
Ph: +1 (604) 259-9564
Mo: +1 (604) 916-2281

**Comment by i-make-robots** [comment]
@devburke please take a picture of the machine and email it to dan@marginallyclever.com.  I was running tests yesterday on a 2.5.2 and everything seemed fine.  maybe 1/3 as fast as a makelangelo 3.

**Comment by devburke** [comment]
Unfortunately, I won't be able to any more. I'm not in the same place any more, and won't be back with the Makelangelo for at least several months.

**Comment by i-make-robots** [comment]
Please let me know if it is still wasting time and I will reopen this issue.
