### ISSUE TITLE
UI CHANGE NEEDED: Add a "Reload last Image" button

### ISSUE THREAD

**Issue by Joshua-BrownDogGadgets** [MarginallyClever/Makelangelo#184]
The UI needs an "Reload last image" button.  

During normal use people frequently wish to change a setting or style if it didn't meet their needs the first time.

It's needlessly tedious to have to go back and find the file again. This is especially handy if you have a folder with a very large number of images in it.  Having a "Last Image" button would make things much easier.  

This was a Menu option in older versions of the software, and it was quite handy.  We're all sad to see it go in newer versions.

**Comment by i-make-robots** [comment]
I had no evidence that it was a desired feature.  That's good to know.  I'll see about putting it back in.

**Comment by i-make-robots** [comment]
This morning I looked into how to do this.  I'm disappointed it will mean an extra layer of popups - one to say "here is the last file you opened [pick a new one] [next step]"

**Comment by Joshua-BrownDogGadgets** [comment]
Or you could just add a button.  Something that says "Reload Last Image".

No need for pop ups.  It would make choosing a design or tweaking designs a
whole lot easier.

From our normal use of the software at shows, exhibits, and in our offices
this button would be frequently used.  Far far more than the "Generate Art"
button, for instance.  (We rare use that except for tests.)

On Mon, Jun 13, 2016 at 1:06 PM, Dan Royer <notifications@github.com> wrote:

> This morning I looked into how to do this. I'm disappointed it will mean
> an extra layer of popups - one to say "here is the last file you opened
> [pick a new one] [next step]"
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/MarginallyClever/Makelangelo/issues/184#issuecomment-225661404>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AS7cT_1L1_XGZf8MwXpVeFSaPrHPIdLqks5qLZw8gaJpZM4IymKh>
> .
>



-- 
Joshua Zimmerman
BrownDogGadgets.com
P: 262-788-9223
C: 262-290-6630

**Comment by i-make-robots** [comment]
Please grab the latest master branch, test the change, and let me know if it works for you.
