### ISSUE TITLE
reset all preferences option

### ISSUE THREAD

**Issue by i-make-robots** [MarginallyClever/Makelangelo#74]
We miss test cases.  An automated test system would want to be able to reset all preferences and delete all temporary files so that it could test clean.

Could this be done as a deeply hidden menu option or would it need to be a separate app?  I'm concerned some classes would finalize() and safe prefs() after whatever bombedBackToTheRoaches() method is called.

**Comment by virtuoushub** [comment]
@i-make-robots I am in the process of coming up with some unit tests. I plan to try and pick certain [single responsibility principled methods](http://en.wikipedia.org/wiki/Single_responsibility_principle) to get started with. That and I also need to hook up a running instance of the application to a profiler and see which pieces of code get called the most. Hello [Pareto principle](http://en.wikipedia.org/wiki/Pareto_principle). :smile: 

When looking at the code using java.util.prefs.Preferences#userRoot in relation to #72 I noticed some places that could use a little love. However without unit tests for regression I did not feel comfortable performing surgery.

I will report back when I have some unit tests completed.

**Comment by virtuoushub** [comment]
See:
* [com.marginallyclever.makelangelo.PreferencesHelperTest#clearAll(Preferences)](https://github.com/MarginallyClever/Makelangelo/blob/dev/java/src/test/java/com/marginallyclever/makelangelo/PreferencesHelperTest.java#L163-#L185)
* [com.marginallyclever.makelangelo.PreferencesHelperTest#shallowClearPreferences(Preferences)](https://github.com/MarginallyClever/Makelangelo/blob/dev/java/src/test/java/com/marginallyclever/makelangelo/PreferencesHelperTest.java#L187-#L199)
* [com.marginallyclever.makelangelo.PreferencesHelperTest#deepClearPreferences(Preferences)](https://github.com/MarginallyClever/Makelangelo/blob/dev/java/src/test/java/com/marginallyclever/makelangelo/PreferencesHelperTest.java#L201-L217)

None of those methods are currently being called as they are destructive and I have not publicly implemented the ["export preference nodes to flat file"](https://github.com/MarginallyClever/Makelangelo/pull/115#issuecomment-112886689) method to backup preference node values.

**Comment by i-make-robots** [comment]
I'll wait.  I'm still using current prefs for the public displays I'm doing
in downtown St. Petersburg.  Playing it safe.

You are some kind of genius, you know that?  I have no talent for what you
do.  Blows my mind every time.

Dan

On Wed, Jun 17, 2015 at 9:05 PM, Peter Colapietro <notifications@github.com>
wrote:

> See:
>
>    -
>    com.marginallyclever.makelangelo.PreferencesHelperTest#clearAll(Preferences)
>    <https://github.com/MarginallyClever/Makelangelo/blob/dev/java/src/test/java/com/marginallyclever/makelangelo/PreferencesHelperTest.java#L163-%23L185>
>    -
>    com.marginallyclever.makelangelo.PreferencesHelperTest#shallowClearPreferences(Preferences)
>    <https://github.com/MarginallyClever/Makelangelo/blob/dev/java/src/test/java/com/marginallyclever/makelangelo/PreferencesHelperTest.java#L187-%23L199>
>    -
>    com.marginallyclever.makelangelo.PreferencesHelperTest#deepClearPreferences(Preferences)
>    <https://github.com/MarginallyClever/Makelangelo/blob/dev/java/src/test/java/com/marginallyclever/makelangelo/PreferencesHelperTest.java#L201-L217>
>
> None of those methods are currently being called as they are destructive
> and I have not publicly implemented the "export preference nodes to flat
> file"
> <https://github.com/MarginallyClever/Makelangelo/pull/115#issuecomment-112886689>
> method to backup preference node values.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarginallyClever/Makelangelo/issues/74#issuecomment-112897478>
> .
>



-- 
Dan Royer :: Marginally Clever <http://www.marginallyclevergroup.com/> ::
Raising Robot Literacy :: +1.604.916.2281

**Comment by i-make-robots** [comment]
Any news on this save to flat file (json?) and back?  I'm blowing up my
settings during my downtime because I've got a machine numbered -1 and it's
breaking the production build.  No option to delete a single machine number
from configs.  Whoops.

On Wed, Jun 17, 2015 at 1:24 PM, Dan Royer <dan@marginallyclever.com> wrote:

> I'll wait.  I'm still using current prefs for the public displays I'm
> doing in downtown St. Petersburg.  Playing it safe.
>
> You are some kind of genius, you know that?  I have no talent for what you
> do.  Blows my mind every time.
>
> Dan
>
> On Wed, Jun 17, 2015 at 9:05 PM, Peter Colapietro <
> notifications@github.com> wrote:
>
>> See:
>>
>>    -
>>    com.marginallyclever.makelangelo.PreferencesHelperTest#clearAll(Preferences)
>>    <https://github.com/MarginallyClever/Makelangelo/blob/dev/java/src/test/java/com/marginallyclever/makelangelo/PreferencesHelperTest.java#L163-%23L185>
>>    -
>>    com.marginallyclever.makelangelo.PreferencesHelperTest#shallowClearPreferences(Preferences)
>>    <https://github.com/MarginallyClever/Makelangelo/blob/dev/java/src/test/java/com/marginallyclever/makelangelo/PreferencesHelperTest.java#L187-%23L199>
>>    -
>>    com.marginallyclever.makelangelo.PreferencesHelperTest#deepClearPreferences(Preferences)
>>    <https://github.com/MarginallyClever/Makelangelo/blob/dev/java/src/test/java/com/marginallyclever/makelangelo/PreferencesHelperTest.java#L201-L217>
>>
>> None of those methods are currently being called as they are destructive
>> and I have not publicly implemented the "export preference nodes to flat
>> file"
>> <https://github.com/MarginallyClever/Makelangelo/pull/115#issuecomment-112886689>
>> method to backup preference node values.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/MarginallyClever/Makelangelo/issues/74#issuecomment-112897478>
>> .
>>
>
>
>
> --
> Dan Royer :: Marginally Clever <http://www.marginallyclevergroup.com/> ::
> Raising Robot Literacy :: +1.604.916.2281
>



-- 
Dan Royer :: Marginally Clever <http://www.marginallyclevergroup.com/> ::
Raising Robot Literacy :: +1.604.916.2281

**Comment by virtuoushub** [comment]
@i-make-robots see #127 to store preferences as flat file and #125 on how to remove machine's numbered anything less than 0.

**Comment by i-make-robots** [comment]
Save to prefs and clear prefs work.  Does reload prefs work for you?  We may be able to close this issue.

**Comment by i-make-robots** [comment]
Closing because my tests say it's ok.  Will reopen if needed.
