### ISSUE TITLE
Wiki update

### ISSUE THREAD

**Issue by virtuoushub** [MarginallyClever/Makelangelo#79]
The documentation on the wiki is now outdated. Some slight tweaks are necessary to have it be pertinent to the current codebase. 

See:
* https://github.com/MarginallyClever/Makelangelo/wiki#download
* https://github.com/MarginallyClever/Makelangelo/wiki#steps

**Comment by i-make-robots** [comment]
Good point.  Can you please suggest changes?

**Comment by virtuoushub** [comment]
I updated the wiki with some of what I was thinking about as being necessary for getting up to speed as a developer. I believe the tweaks you and I made update the wiki sufficiently for the time being. I am closing this for now, however if the wiki needs to be updated and revisited in the future I will link back to this issue and further flesh out some suggested changes.

**Comment by i-make-robots** [comment]
maybe a note in pom.xml to say "hey!  You're changing maven, maybe update
the wiki, too."

On Sun, May 10, 2015 at 1:56 PM, Peter Colapietro <notifications@github.com>
wrote:

> I updated the wiki with some of what I was thinking about as being
> necessary for getting up to speed as a developer. I believe the tweaks you
> and I made update the wiki sufficiently for the time being. I am closing
> this for now, however if the wiki needs to be updated and revisited in the
> future I will link back to this issue and further flesh out some suggested
> changes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarginallyClever/Makelangelo/issues/79#issuecomment-100701175>
> .
>



-- 
Dan Royer :: Marginally Clever <http://www.marginallyclevergroup.com/> ::
Raising Robot Literacy :: +1.604.916.2281
