### ISSUE TITLE
Provide user with better notification when they are converting an image file into G-code

### ISSUE THREAD

**Issue by virtuoushub** [MarginallyClever/Makelangelo#80]
I have noticed that after pressing "Load File..." under the GCODE tab, and selecting you conversation style/configuration, the application will not indicate to the user that anything is happening unless you explicitly click on the Log tab.

I found this not to be as intuitive as I would want. One possible solution is to open the log after you open a file.

**Comment by i-make-robots** [comment]
A progress bar would also be good.  there are many non-translated strings in here. :T

**Comment by i-make-robots** [comment]
I will auto-tab to Log window when a conversion begins.  A progress bar with a cancel button would be better, but AFAIK it means putting all conversions into a separate thread and that's a lot of work that won't happen before mile 8
