### ISSUE TITLE
Translate Hardcoded Strings

### ISSUE THREAD

**Issue by virtuoushub** [MarginallyClever/Makelangelo#81]
There are ~~a lot of~~ hard coded english strings used throughout the source. These need to be pulled out into the language files.

See @i-make-robots' [comment](https://github.com/MarginallyClever/Makelangelo/issues/80#issuecomment-95768324) for #80 

Example:

https://github.com/MarginallyClever/Makelangelo/blob/dev/java/src/main/java/com/marginallyclever/drawingtools/DrawingTool_Pen.java#L48

**Comment by i-make-robots** [comment]
All menu hardcoded strings have been pulled out.  I didn't bother with the log messages because most people shouldn't have to see them.
