### ISSUE TITLE
load gcode with no machine configurations causes exception

### ISSUE THREAD

**Issue by i-make-robots** [MarginallyClever/Makelangelo#92]

**Comment by virtuoushub** [comment]
@i-make-robots, does this still happen in the development branch?

**Comment by i-make-robots** [comment]
I don't know, I'd have to wipe out all my configs to test it.

On Mon, Jun 22, 2015 at 9:13 AM, Peter Colapietro <notifications@github.com>
wrote:

> @i-make-robots <https://github.com/i-make-robots>, does this still happen
> in the development branch?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarginallyClever/Makelangelo/issues/92#issuecomment-114168145>
> .
>



-- 
Dan Royer :: Marginally Clever <http://www.marginallyclevergroup.com/> ::
Raising Robot Literacy :: +1.604.916.2281

**Comment by virtuoushub** [comment]
Have you tested this now that you can import/export configurations via #132?

**Comment by i-make-robots** [comment]
I've exported and wiped. on wipe the menus don't update.  Maybe it should
popup a "restart now?" option to reset the menus.

Can we make export and import into "save" and "load"?  We already have
translations for those strings :)



On Tue, Sep 1, 2015 at 5:21 AM, Peter Colapietro <notifications@github.com>
wrote:

> Have you tested this now that you can import/export configurations via
> #132 <https://github.com/MarginallyClever/Makelangelo/pull/132>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarginallyClever/Makelangelo/issues/92#issuecomment-136694050>
> .
>



-- 
Dan Royer :: Marginally Clever <http://www.marginallyclevergroup.com/> ::
Raising Robot Literacy :: +1.604.916.2281

**Comment by i-make-robots** [comment]
Seems to work great.  Nicely done!


On Tue, Sep 1, 2015 at 6:24 AM, Dan Royer <dan@marginallyclever.com> wrote:

> I've exported and wiped. on wipe the menus don't update.  Maybe it should
> popup a "restart now?" option to reset the menus.
>
> Can we make export and import into "save" and "load"?  We already have
> translations for those strings :)
>
>
>
> On Tue, Sep 1, 2015 at 5:21 AM, Peter Colapietro <notifications@github.com
> > wrote:
>
>> Have you tested this now that you can import/export configurations via
>> #132 <https://github.com/MarginallyClever/Makelangelo/pull/132>?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/MarginallyClever/Makelangelo/issues/92#issuecomment-136694050>
>> .
>>
>
>
>
> --
> Dan Royer :: Marginally Clever <http://www.marginallyclevergroup.com/> ::
> Raising Robot Literacy :: +1.604.916.2281
>



-- 
Dan Royer :: Marginally Clever <http://www.marginallyclevergroup.com/> ::
Raising Robot Literacy :: +1.604.916.2281

**Comment by i-make-robots** [comment]
Is there an automated test?

**Comment by i-make-robots** [comment]
Best solution is to have a default config already available on first program start.  Then there will always be a MachineConfiguration loaded.

**Comment by i-make-robots** [comment]
will reopen if the bug reappears, but we haven't seen or heard of it in a long time.
