### ISSUE TITLE
first load on new install causes non-fatal exception

### ISSUE THREAD

**Issue by i-make-robots** [MarginallyClever/Makelangelo#93]
can't create prefs root node.  I don't have the exact text.  windows 8.1 w/ java 1.8
error appears in v7.1.0 zip download

**Comment by virtuoushub** [comment]
possibly related to #72.

Closing #74 goes a long way to ensure future releases do not contain preference node related issues. When you get a chance please look into accepting #95 as I think it will help when creating unit tests for these types of things.

**Comment by i-make-robots** [comment]
I would have gone faster, I was travelling all day yesterday.

On Tue, May 19, 2015 at 3:19 AM, Peter Colapietro <notifications@github.com>
wrote:

> possibly related to #72
> <https://github.com/MarginallyClever/Makelangelo/issues/72>.
>
> Closing #74 <https://github.com/MarginallyClever/Makelangelo/issues/74>
> goes a long way to ensure future releases do not contain preference node
> related issues. When you get a chance please look into accepting #95
> <https://github.com/MarginallyClever/Makelangelo/pull/95> as I think it
> will help when creating unit tests for these types of things.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarginallyClever/Makelangelo/issues/93#issuecomment-103428248>
> .
>



-- 
Dan Royer :: Marginally Clever <http://www.marginallyclevergroup.com/> ::
Raising Robot Literacy :: +1.604.916.2281

**Comment by virtuoushub** [comment]
Unless this is different that what @chrsmlls333 [observed](https://github.com/MarginallyClever/Makelangelo/issues/97#issuecomment-104853682), than this is [not actually an issue](https://github.com/MarginallyClever/Makelangelo/issues/97#issuecomment-105095394).

Also this is most likely not related to #72.

**Comment by i-make-robots** [comment]
expected or not, we'll keep hearing about it until it stops happening.  Is there a known fix?  asking everyone to modify their java settings is unreasonable.

**Comment by virtuoushub** [comment]
One suggested fix is creating the missing registry key. On Windows, which to my knowledge is the only place this warning occurs, you need to do this as an administrator. IMHO this is just as unreasonable as asking everyone to modify the logging settings for their java.

Another is to change the logging level for the `java.util.prefs`, I am not sure if this can be done outside of the JVM level however I have created a [PR](https://github.com/MarginallyClever/Makelangelo/pull/107) to see if our logging framework facade, SLF4J, will handle it.

To be clear the message @chrsmlls333 was seeing was only a warning and had no effect on Makelangelo's behavior. I agree that making it stop happening is ideal, right now I have tried to document and workaround the issue. I do not really like changing the logging level for a specific package just to make the warning not visible however I see no alternative option short of having a Windows administrator create the missing registry keys.

**Comment by i-make-robots** [comment]
Could the windows start.bat file do it?

On Sat, May 30, 2015 at 9:01 AM, Peter Colapietro <notifications@github.com>
wrote:

> One suggested fix is creating the missing registry key. On Windows, which
> to my knowledge is the only place this warning occurs, you need to do this
> as an administrator. IMHO this is just as unreasonable as asking everyone
> to modify the logging settings for their java.
>
> Another is to change the logging level for the java.util.prefs, I am not
> sure if this can be done outside of the JVM level however I have created a
> PR <https://github.com/MarginallyClever/Makelangelo/pull/107> to see if
> our logging framework facade, SLF4J, will handle it.
>
> To be clear the message @chrsmlls333 <https://github.com/chrsmlls333> was
> seeing was only a warning and had no effect on Makelangelo's behavior. I
> agree that making it stop happening is ideal, right now I have tried to
> document and workaround the issue. I do not really like changing the
> logging level for a specific package just to make the warning not visible
> however I see no alternative option short of having a Windows administrator
> create the missing registry keys.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarginallyClever/Makelangelo/issues/93#issuecomment-107057040>
> .
>



-- 
Dan Royer :: Marginally Clever <http://www.marginallyclevergroup.com/> ::
Raising Robot Literacy :: +1.604.916.2281

**Comment by virtuoushub** [comment]
Yes, the logic to add the missing registry key could be added to [start windows.bat](https://github.com/MarginallyClever/Makelangelo/blob/master/last_official_release/Makelangelo/start%20windows.bat), however in order for it to work the batch file needs to be run by an administrator. This might not always be possible. I do not recommend this solution.

Thinking about it more, the extended Preferences API idea seems like the way to do it. While writing unit tests to help close #74, an API could also be written.

I was thinking files containing the preferences as JSON data would be used. Do you have any objection to this approach? In this way preferences like machine configurations could be easily imported/exported and viewed/edited in a pretty human readable format.

**Comment by i-make-robots** [comment]
I don't mind.  The same JSON could later be sync'd in the cloud for those
who want to back up their settings.


On Sat, May 30, 2015 at 2:34 PM, Peter Colapietro <notifications@github.com>
wrote:

> Yes, the logic to add the missing registry key could be added to start
> windows.bat
> <https://github.com/MarginallyClever/Makelangelo/blob/master/last_official_release/Makelangelo/start%20windows.bat>,
> however in order for it to work the batch file needs to be run by an
> administrator. This might not always be possible. I do not recommend this
> solution.
>
> Thinking about it more, the extended Preferences API idea seems like the
> way to do it. While writing unit tests to help close #74
> <https://github.com/MarginallyClever/Makelangelo/issues/74>, an API could
> also be written.
>
> I was thinking files containing the preferences as JSON data would be
> used. Do you have any objection to this approach? In this way preferences
> like machine configurations could be easily imported/exported and
> viewed/edited in a pretty human readable format.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarginallyClever/Makelangelo/issues/93#issuecomment-107090103>
> .
>



-- 
Dan Royer :: Marginally Clever <http://www.marginallyclevergroup.com/> ::
Raising Robot Literacy :: +1.604.916.2281

**Comment by i-make-robots** [comment]
I have tested for this bug and am unable to reproduce it any more.  Is it closed?  Does clearing out the prefs actually delete the root pref node for makelangelo and recreate this situation?

**Comment by i-make-robots** [comment]
Tested, seems OK.  Is there an automated test to keep this bug dead?
